version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are calles later in the workflows sections
jobs:
  automate:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/node:14.15"
    steps:
      - checkout
      - node/install:
          node-version: "14.15"
      - eb/setup
      - aws-cli/setup
      # Use root level package.json to install dependencies in the frontend app
      #install the api
      - run:
          name: Install API Dependencies
          command: |
            npm run api:install
      #api build
      - run:
          name: API Build
          command: |
            npm run api:build

      #install frontend
      - run:
          name: Install Front-End Dependencies
          command: |
            echo "NODE --version" 
            echo $(node --version)
            echo "NPM --version" 
            echo $(npm --version)
            npm run frontend:install
            npm install typescript@">=3.4.0 and <3.6.0" --save-dev
      #frontend lint
      #- run:
      #name: Front-End Lint
      #command: |
      #npm run frontend:lint
      #frontend build
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      #api deploy
      - run:
          name: API deploy
          command: |
            npm run api:deploy
      #frontend deploy
      - run:
          name: Front-End deploy
          command: |
            npm run frontend:deploy
            #install api

workflows:
  udagram:
    jobs:
      - automate:
          filters:
            branches:
              only: master
